ALTER TABLE raw.raw_fixtures
ALTER COLUMN season SET NOT NULL,
ALTER COLUMN league SET NOT NULL,
ALTER COLUMN country SET NOT NULL,
ALTER COLUMN home_team_name SET NOT NULL,
ALTER COLUMN away_team_name SET NOT NULL,
ALTER COLUMN fixture_id SET NOT NULL,
ALTER COLUMN match_status SET NOT NULL;
