version: 2

models:
  - name: mart_top_team_streaks
    description: "Current (most recent) team streaks per event with length > 2 for the current season."
    columns:
      - name: streak_id
        description: "Display-only row number; not stable across runs."
      - name: league_name
        description: "League display name from stg_dim_leagues."
        tests: [not_null]
      - name: team_name
        description: "Team display name from stg_dim_teams."
        tests: [not_null]
      - name: event_name
        description: "Event label (e.g. win, clean_sheet, score_2goals...)."
        tests: [not_null]
      - name: streak_type
        description: "Event category."
        tests:
          - accepted_values:
              values: ['goal_streaks','result_streaks','special_streaks']
      - name: current_streak_length
        description: "Latest run-length; model filters to values > 2."
        tests:
          - not_null
        