version: 2

models:
  - name: mart_latest_team_streaks
    description: |
      Provides, for each team and event type, the most recent streak count
      of consecutive occurrences up to the latest match.
    columns:
      - name: team_name
        description: "The official name of the team."
        tests:
          - not_null

      - name: event_name
        description: |
          The type of event that defines the streak, 
          for example 'goal_scored' or 'goal_conceded'.
        tests:
          - not_null

      - name: streak_count
        description: |
          The number of consecutive matches in which the specified event 
          occurred, counted up to the most recent fixture.
        tests:
          - not_null